```{r 11-remove-all, include = FALSE}
rm(list = ls())
```


## Basics for visualisation in R using {ggplot2}

<details><summary>*Click here to show setup code.*</summary>
```{r include = FALSE}
### Basics for visualisation in R using {ggplot2}

```
```{r 11-setup-11-mpg-r}
library(tidyverse)
```
</details>


```{r include = FALSE}
# # One time:
# install.packages("tidyverse")
```
```{r 11-one-time}

```


```{r include = FALSE}
# Empty graph
```
```{r 11-empty-graph}
ggplot(
  data = mpg,
  mapping = aes(x = displ, y = hwy)
)
```


```{r include = FALSE}
# Scatterplot
```
```{r 11-scatterplot}
ggplot(
  data = mpg,
  mapping = aes(x = displ, y = hwy)
) +
  geom_point()
```


```{r include = FALSE}
# aes() determines which variables are plotted
```
```{r 11-aes-determines-which-variables-are-plotted}
ggplot(
  data = mpg,
  mapping = aes(x = cyl, y = hwy)
) +
  geom_point()
```


```{r include = FALSE}
# Pattern unchanged if only variables are plotted
```
```{r 11-pattern-unchanged-if-only-variables-are-plotted}
ggplot(
  data = mpg,
  mapping = aes(x = hwy, y = cty)
) +
  geom_point()
```
