```{r 12-remove-all, include = FALSE}
rm(list = ls())
```


## Tweaks and tricks

<details><summary>*Click here to show setup code.*</summary>
```{r include = FALSE}
### Tweaks and tricks

```
```{r 12-setup-12-manual-r}
library(tidyverse)
```
</details>


```{r include = FALSE}
# chose color in geom
```
```{r 12-chose-color-in-geom}
ggplot(
  data = mpg,
  mapping = aes(x = displ, y = hwy)
) +
  geom_point(
    color = "red"
  )
```


```{r include = FALSE}
# different color 1
```
```{r 12-different-color-1}
ggplot(
  data = mpg,
  mapping = aes(x = displ, y = hwy)
) +
  geom_point(
    color = "blue"
  )
```


```{r include = FALSE}
# different color 2
```
```{r 12-different-color-2}
ggplot(
  data = mpg,
  mapping = aes(x = displ, y = hwy)
) +
  geom_point(
    color = "green"
  )
```


```{r include = FALSE}
# color as 3rd axis
```
```{r 12-color-as-3-rd-axis}
ggplot(
  data = mpg,
  mapping = aes(x = displ, y = hwy, color = class)
) +
  geom_point()
```


```{r include = FALSE}
# point shape as 3rd axis
```
```{r 12-point-shape-as-3-rd-axis}
ggplot(
  data = mpg,
  mapping = aes(
    x = displ,
    y = hwy,
    shape = class
  )
) +
  geom_point()
```


```{r include = FALSE}
# shape mapped on drv
```
```{r 12-shape-mapped-on-drv}
ggplot(
  data = mpg,
  mapping = aes(
    x = displ,
    y = hwy,
    shape = drv
  )
) +
  geom_point()
```


```{r include = FALSE}
# point size as 3rd axis
```
```{r 12-point-size-as-3-rd-axis}
ggplot(
  data = mpg,
  mapping = aes(
    x = displ,
    y = hwy,
    size = cty
  )
) +
  geom_point()
```


```{r include = FALSE}
# mix to increase axis num
```
```{r 12-mix-to-increase-axis-num}
ggplot(
  data = mpg,
  mapping = aes(
    x = displ,
    y = hwy,
    color = class,
    size = cty
  )
) +
  geom_point()
```


```{r include = FALSE}
# unquoted col in aes()
```
```{r 12-unquoted-col-in-aes}
ggplot(
  data = mpg,
  mapping = aes(
    x = displ,
    y = hwy,
    color = blue
  )
) +
  geom_point()
```


```{r include = FALSE}
# mpg quoted and unquoted
```
```{r 12-mpg-quoted-and-unquoted}
mpg
"mpg"
```


```{r include = FALSE}
# quoted color in aes()
```
```{r 12-quoted-color-in-aes}
ggplot(
  data = mpg,
  mapping = aes(
    x = displ,
    y = hwy,
    color = "blue"
  )
) +
  geom_point()
```


```{r include = FALSE}
# semi-transparency
```
```{r 12-semi-transparency}
ggplot(
  data = mpg,
  mapping = aes(
    x = displ,
    y = hwy
  )
) +
  geom_point(alpha = 0.2)
```


```{r include = FALSE}
# function of variables in aes()
```
```{r 12-function-of-variables-in-aes}
ggplot(
  data = mpg,
  mapping = aes(
    x = displ,
    y = 2.35 / hwy
  )
) +
  geom_point()
```


```{r include = FALSE}
# color in geom()
```
```{r 12-color-in-geom}
ggplot(
  data = mpg,
  mapping = aes(
    x = displ,
    y = 2.35 / hwy
  )
) +
  geom_point(color = class)
```
