```{r 13-remove-all, include = FALSE}
rm(list = ls())
```


## Labels and layers

<details><summary>*Click here to show setup code.*</summary>
```{r include = FALSE}
### Labels and layers

```
```{r 13-setup-13-other-r}
library(tidyverse)
```
</details>


```{r include = FALSE}
# geom_text()
```
```{r 13-geom-text}
ggplot(
  data = mpg,
  mapping = aes(x = displ, y = hwy)
) +
  geom_text(label = "A")
```


```{r include = FALSE}
# set label in aes() for geom_text()
```
```{r 13-set-label-in-aes-for-geom-text}
ggplot(
  data = mpg,
  mapping = aes(x = displ, y = hwy, label = "drv")
) +
  geom_text()
```


```{r include = FALSE}
# 3rd axis as label for geom_text()
```
```{r 13-3-rd-axis-as-label-for-geom-text}
ggplot(
  data = mpg,
  mapping = aes(x = displ, y = hwy, label = drv)
) +
  geom_text()
```


```{r include = FALSE}
# Two layers
```
```{r 13-two-layers}
ggplot(
  data = mpg,
  mapping = aes(x = displ, y = hwy, label = drv)
) +
  geom_point() +
  geom_text()
```


```{r include = FALSE}
# Two layers more clearly
```
```{r 13-two-layers-more-clearly}
ggplot(
  data = mpg,
  mapping = aes(x = displ, y = hwy, label = drv)
) +
  geom_point(color = "blue") +
  geom_text(size = 10)
```


```{r include = FALSE}
# Global and local aesthetic mappings
```
```{r 13-global-and-local-aesthetic-mappings}
ggplot(
  data = mpg,
  mapping = aes(x = displ, y = hwy)
) +
  geom_point(color = "blue") +
  geom_text(
    mapping = aes(color = class, label = drv),
    size = 10,
    alpha = 0.2
  )
```


```{r include = FALSE}
# Good:
```
```{r 13-good}
ggplot(
  data = mpg,
  mapping = aes(x = displ, y = hwy)
) +
  geom_point() +
  geom_rug()
```


```{r include = FALSE}
# Bad:
```
```{r 13-bad}
ggplot(
  data = mpg
) +
  geom_point(mapping = aes(x = displ, y = hwy)) +
  geom_rug(mapping = aes(x = displ, y = hwy))
```


```{r include = FALSE}
# Broken:
```
```{r 13-broken}
ggplot(
  data = mpg
) +
  geom_point(mapping = aes(x = displ, y = hwy)) +
  geom_rug(mapping = aes(x = displ, y = cty))
```


```{r include = FALSE}
# Smooth
```
```{r 13-smooth}
ggplot(
  data = mpg,
  mapping = aes(x = displ, y = hwy)
) +
  geom_point() +
  geom_smooth()
```


```{r include = FALSE}
# smooth method linear model
```
```{r 13-smooth-method-linear-model}
ggplot(
  data = mpg,
  mapping = aes(x = displ, y = hwy)
) +
  geom_point() +
  geom_smooth(method = "lm")
```
