```{r 403-remove-all, include = FALSE}
rm(list = ls())
```


## <No caption defined>

<details><summary>*Click here to show setup code.*</summary>
```{r include = FALSE}
### <No caption defined>

```
```{r 403-setup-403-ftable-r}
library(tidyverse)
library(nycflights13)

library(conflicted)
conflict_prefer("filter", "dplyr")
conflict_prefer("lag", "dplyr")
```
</details>


```{r include = FALSE}
# Formatting for presentation with ftable()
```
```{r 403-formatting-for-presentation-with-ftable}
table2 %>%
  xtabs(count ~ ., .) %>%
  ftable()
```


```{r include = FALSE}
# Deciding what goes into the columns, what into the rows
```
```{r 403-deciding-what-goes-into-the-columns-what-into-the-rows}
table2 %>%
  xtabs(count ~ ., .) %>%
  ftable(col.vars = c("year", "type"))
```


```{r include = FALSE}
# gt package
```
```{r 403-gt-package}

```


```{r include = FALSE}
# reporttools package
```
```{r 403-reporttools-package}

?`tidyr-package`
```


```{r include = FALSE}
# https://tidyr.tidyverse.org/
```
```{r 403-https-tidyr-tidyverse-org}
NA
```
