```{r 41-remove-all, include = FALSE}
rm(list = ls())
```


## Pivoting

<details><summary>*Click here to show setup code.*</summary>
```{r include = FALSE}
### Pivoting

```
```{r 41-setup-41-spread-r}
library(tidyverse)
library(nycflights13)

library(conflicted)
conflict_prefer("filter", "dplyr")
conflict_prefer("lag", "dplyr")
```
</details>


```{r include = FALSE}
# Two datasets containing the same data, wider and longer:
```
```{r 41-two-datasets-containing-the-same-data-wider-and-longer}
table1
table2
```


```{r include = FALSE}
# How to summarize?
```
```{r 41-how-to-summarize}
table1 %>%
  group_by(country) %>%
  summarize(
    max_cases = max(cases),
    max_population = max(population)
  )
```


```{r include = FALSE}
# Iterate over columns:
```
```{r 41-iterate-over-columns}
table1 %>%
  group_by(country) %>%
  summarize_at(
    vars(cases, population),
    max
  )
```


```{r include = FALSE}
# In the longer form, this becomes a grouped operation:
```
```{r 41-in-the-longer-form-this-becomes-a-grouped-operation}
table2 %>%
  group_by(country, type) %>%
  summarize(
    max = max(count)
  )
```


```{r include = FALSE}
# Converting to longer form: pivot_longer()
```
```{r 41-converting-to-longer-form-pivot-longer}
table1

table1 %>%
  pivot_longer(c(-country, -year))
```


```{r include = FALSE}
# Need to rename and arrange to create table1
```
```{r 41-need-to-rename-and-arrange-to-create-table-1}
table1 %>%
  pivot_longer(c(-country, -year)) %>%
  rename(type = name, count = value) %>%
  arrange(country, year, type)

table1 %>%
  pivot_longer(
    c(-country, -year),
    names_to = "type",
    values_to = "count"
  ) %>%
  arrange(country, year, type)
```


```{r include = FALSE}
# Converting to wider form: pivot_wider()
```
```{r 41-converting-to-wider-form-pivot-wider}
table2

table2 %>%
  pivot_wider(names_from = type, values_from = count)

table2 %>%
  rename(name = type, value = count) %>%
  pivot_wider()
```


```{r include = FALSE}
# Longer form: more useful for plotting all values side by side
```
```{r 41-longer-form-more-useful-for-plotting-all-values-side-by-side}
table2 %>%
  ggplot() +
  geom_col(aes(country, count, fill = type), position = "dodge") +
  facet_wrap(~year) +
  scale_y_log10()

table1 %>%
  ggplot() +
  geom_col(aes(country, population), position = "dodge", fill = "blue") +
  geom_col(aes(country, cases), position = "dodge", fill = "red") +
  facet_wrap(~year) +
  scale_y_log10()
```


```{r include = FALSE}
# Wider form: more useful for plotting a single value
```
```{r 41-wider-form-more-useful-for-plotting-a-single-value}
table1 %>%
  ggplot() +
  geom_col(aes(country, cases)) +
  facet_wrap(~year)

table2 %>%
  filter(type == "cases") %>%
  ggplot() +
  geom_col(aes(country, count)) +
  facet_wrap(~year)
```


```{r include = FALSE}
# Wider form: the only way to correlate values
```
```{r 41-wider-form-the-only-way-to-correlate-values}
table1 %>%
  ggplot() +
  geom_point(aes(cases, population, color = factor(year), shape = country)) +
  scale_x_log10() +
  scale_y_log10()
```


```{r include = FALSE}
# Split data
```
```{r 41-split-data}
table4a
table4b
```


```{r include = FALSE}
# Combine
```
```{r 41-combine}
table4 <-
  bind_rows(
    cases = cases_tbl,
    population = population_tbl,
    .id = "type"
  )
table4
```


```{r include = FALSE}
# Imperfect results -- what is missing?
```
```{r 41-imperfect-results-what-is-missing}
table4 %>%
  pivot_longer(c(`1999`, `2000`))
```


```{r include = FALSE}
# WHO data
```
```{r 41-who-data}
who %>%
  view()

who_longer <-
  who %>%
  pivot_longer(
    -(country:year),
    names_pattern = "([a-z_]+)_(.)([0-9]+)",
    names_to = c("type", "sex", "age")
  )

who_longer

who_longer %>%
  count(type, sex)

who_longer %>%
  count(age)
```
