```{r 42-remove-all, include = FALSE}
rm(list = ls())
```


## Separating and uniting

<details><summary>*Click here to show setup code.*</summary>
```{r include = FALSE}
### Separating and uniting

```
```{r 42-setup-42-separate-r}
library(tidyverse)
library(nycflights13)

library(conflicted)
conflict_prefer("filter", "dplyr")
conflict_prefer("lag", "dplyr")
```
</details>


```{r include = FALSE}
# Yet another view at the same data
```
```{r 42-yet-another-view-at-the-same-data}
table3
```


```{r include = FALSE}
# How to split?
```
```{r 42-how-to-split}
table3 %>%
  separate(rate, into = c("cases", "population"))

table3 %>%
  separate(rate, into = c("cases", "population"), sep = "/", convert = TRUE)
```


```{r include = FALSE}
# See help for details
```
```{r 42-see-help-for-details}
?separate
```


```{r include = FALSE}
# Parsing numbers
```
```{r 42-parsing-numbers}
thousand_separator <-
  tribble(
    ~num,
    "1'000.00",
    "2'000'000.00"
  )

thousand_separator
```


```{r include = FALSE}
# separate() doesn't work here
```
```{r 42-separate-doesn-t-work-here}
thousand_separator %>%
  separate(num, into = c("num"))
```


```{r include = FALSE}
# Remove all non-number components
```
```{r 42-remove-all-non-number-components}
thousand_separator %>%
  mutate(num = str_replace_all(num, "[^-0-9.]", "")) %>%
  mutate(num = as.numeric(num))
```


```{r include = FALSE}
# Uniting
```
```{r 42-uniting}
table5

table5 %>%
  unite("year", c(century, year))
```


```{r include = FALSE}
# Not quite done yet:
```
```{r 42-not-quite-done-yet}
table5 %>%
  unite("year", c(century, year), sep = "")

table5 %>%
  unite("year", c(century, year), sep = "") %>%
  mutate(year = as.numeric(year))
```


```{r include = FALSE}
# See help for more info
```
```{r 42-see-help-for-more-info}
?unite
```
