```{r 51-remove-all, include = FALSE}
rm(list = ls())
```


## Plotting: custom labels and scales

<details><summary>*Click here to show setup code.*</summary>
```{r include = FALSE}
### Plotting: custom labels and scales

```
```{r 51-setup-51-scales-r}
library(tidyverse)
library(nycflights13)

library(conflicted)
conflict_prefer("filter", "dplyr")
conflict_prefer("lag", "dplyr")
```
</details>


```{r include = FALSE}
# Base plot
```
```{r 51-base-plot}
ggplot(
  data = mpg,
  mapping = aes(x = displ, y = hwy, color = class)
) +
  geom_point()
```


```{r include = FALSE}
# Add descriptive labels: the labs() function
```
```{r 51-add-descriptive-labels-the-labs-function}
ggplot(
  data = mpg,
  mapping = aes(x = displ, y = hwy, color = class)
) +
  geom_point() +
  labs(
    x = "Displacement",
    y = "Highway mileage\n[miles per gallon]",
    color = "Car class",
    title = "Highway mileages depending on displacement",
    subtitle = "By car class"
  )
```


```{r include = FALSE}
# Change scale to log scale
```
```{r 51-change-scale-to-log-scale}
ggplot(
  data = mpg,
  mapping = aes(x = displ, y = hwy, color = class)
) +
  geom_point() +
  scale_x_log10()
```


```{r include = FALSE}
# Name in scale_() overwrites labs() without warning!
```
```{r 51-name-in-scale-overwrites-labs-without-warning}
ggplot(
  data = mpg,
  mapping = aes(x = displ, y = hwy, color = class)
) +
  geom_point() +
  labs(
    x = "Displacement"
  ) +
  scale_x_log10(name = "xxx")
```


```{r include = FALSE}
# Double log scale
```
```{r 51-double-log-scale}
ggplot(
  data = mpg,
  mapping = aes(x = displ, y = hwy, color = class)
) +
  geom_point() +
  scale_x_log10() +
  scale_y_log10()
```


```{r include = FALSE}
# Change color palette
```
```{r 51-change-color-palette}
ggplot(
  data = mpg,
  mapping = aes(x = displ, y = hwy, color = class)
) +
  geom_point() +
  scale_color_brewer(type = "qual")
```


```{r include = FALSE}
# Other options: viridis
```
```{r 51-other-options-viridis}
ggplot(
  data = mpg,
  mapping = aes(x = displ, y = hwy, color = class)
) +
  geom_point() +
  scale_color_viridis_d(option = "B")
```


```{r include = FALSE}
# Full control: manual scale FIXME
```
```{r 51-full-control-manual-scale-fixme}
ggplot(
  data = mpg,
  mapping = aes(x = displ, y = hwy, color = class)
) +
  geom_point() +
  scale_color_manual(values = c(
    "2seater" = "#000000",
    "compact" = "#3355FF",
    "midsize" = "#006400",
    "minivan" = "#FF5522",
    "pickup" = "#66FFFF",
    "subcompact" = "#FF0000",
    "suv" = "#FF55FF"))
```


```{r include = FALSE}
# For "corporate design": ggthemr, https://github.com/cttobin/ggthemr
```
```{r 51-for-corporate-design-ggthemr-https-github-com-cttobin-ggthemr}
NA
```
