```{r 61-remove-all, include = FALSE}
rm(list = ls())
```


## Joins

<details><summary>*Click here to show setup code.*</summary>
```{r include = FALSE}
### Joins

```
```{r 61-setup-61-join-r}
library(tidyverse)
library(nycflights13)

library(here)

library(conflicted)
conflict_prefer("filter", "dplyr")
conflict_prefer("lag", "dplyr")
```
</details>


```{r include = FALSE}
# `airlines` contain detailed information for each airline
# (in this case only the name)
```
```{r 61-airlines-contain-detailed-information-for-each-airline}
airlines
```


```{r include = FALSE}
# `flights` can be augmented with this detailed information
```
```{r 61-flights-can-be-augmented-with-this-detailed-information}
flights %>%
  left_join(airlines) %>%
  select(dep_time, carrier, name)
```


```{r include = FALSE}
# for "production code", always indicate the columns to join by
```
```{r 61-for-production-code-always-indicate-the-columns-to-join-by}
flights %>%
  left_join(airlines, by = "carrier") %>%
  select(dep_time, carrier, name)
```


```{r include = FALSE}
# Your turn: join the `planes` table
```
```{r 61-your-turn-join-the-planes-table}
planes
```


```{r include = FALSE}
# Does it work out of the box?
```
```{r 61-does-it-work-out-of-the-box}
try(
  ... %>%
    ..._join(...)
)
```


```{r include = FALSE}
# How to fix, and also turn off the message?
```
```{r 61-how-to-fix-and-also-turn-off-the-message}
try(
  ... %>%
    ..._join(..., ... = "...")
)
```


```{r include = FALSE}
# `airports` contain detailed information for each airport
```
```{r 61-airports-contain-detailed-information-for-each-airport}
airports

try(
  flights %>%
    left_join(airports)
)
```


```{r include = FALSE}
# in this case, explicit "by" columns are required
```
```{r 61-in-this-case-explicit-by-columns-are-required}
flights %>%
  left_join(airports, by = c("dest" = "faa")) %>%
  select(origin, dest, name)
```


```{r include = FALSE}
# we have mismatches!
```
```{r 61-we-have-mismatches}
flights %>%
  left_join(airports, by = c("dest" = "faa")) %>%
  select(origin, dest, name) %>%
  filter(is.na(name))
```


```{r include = FALSE}
# what about the NA name?
```
```{r 61-what-about-the-na-name}
airports %>%
  filter(faa == "BQN")
```


```{r include = FALSE}
# left vs. inner vs. outer joins control what happens in case of mismatches
```
```{r 61-left-vs-inner-vs-outer-joins-control-what-happens-in-case-of-mismatches}
flights %>%
  inner_join(airports, by = c("dest" = "faa")) %>%
  select(origin, dest, name)
```


```{r include = FALSE}
# Your turn: understand mismatches when joining the `planes` data
```
```{r 61-your-turn-understand-mismatches-when-joining-the-planes-data}
try(
  ... %>%
    left_join(..., ... = "...") %>%
    filter(is.na(...))
)
```


```{r include = FALSE}
# Verify that "AA" has more mismatches than other airlines
```
```{r 61-verify-that-aa-has-more-mismatches-than-other-airlines}
try(
  ... %>%
    left_join(..., ... = "...") %>%
    mutate(mismatch = is.na(...), is_aa = (carrier == "AA")) %>%
    count(.....)
)
```


```{r include = FALSE}
# How to keep only the flights where we have airplane details?
```
```{r 61-how-to-keep-only-the-flights-where-we-have-airplane-details}
try(
  ... %>%
    ..._join(..., ... = "...")
)
```


```{r include = FALSE}
# Case study: classification of mismatches
```
```{r 61-case-study-classification-of-mismatches}
flights %>%
  left_join(planes %>% select(tailnum, manufacturer), by = "tailnum") %>%
  mutate(mismatch = is.na(manufacturer)) %>%
  select(-tailnum, -manufacturer) %>%
  rpart::rpart(mismatch ~ ., .)
```


```{r include = FALSE}
# before joining, prepare the RHS table(s)
```
```{r 61-before-joining-prepare-the-rhs-table-s}
origin_airports <-
  airports %>%
  select(origin = faa, origin_name = name)

origin_airports

dest_airports <-
  airports %>%
  select(dest = faa, dest_name = name)

dest_airports
```


```{r include = FALSE}
# much easier with the prepared tables
```
```{r 61-much-easier-with-the-prepared-tables}
flights %>%
  left_join(origin_airports) %>%
  left_join(dest_airports) %>%
  select(origin, origin_name, dest, dest_name)
```


```{r include = FALSE}
# "by" still recommended
```
```{r 61-by-still-recommended}
flights %>%
  left_join(origin_airports, by = "origin") %>%
  left_join(dest_airports, by = "dest") %>%
  select(origin, origin_name, dest, dest_name)
```


```{r include = FALSE}
# Your turn: we only need `engines` and `seats` from the `planes` table
```
```{r 61-your-turn-we-only-need-engines-and-seats-from-the-planes-table}
try({
  planes_join <-
    ... %>%
    ...(...)

  ... %>%
    left_join(..., ... = "...")
})
```


```{r include = FALSE}
# either LHS or RHS should have a key as part of "by"
```
```{r 61-either-lhs-or-rhs-should-have-a-key-as-part-of-by}
airports %>%
  count(faa)

airports %>%
  count(faa) %>%
  count(n)
```


```{r include = FALSE}
# Your turn: double-check that `tailnum` is indeed a key in `planes`
```
```{r 61-your-turn-double-check-that-tailnum-is-indeed-a-key-in-planes}
try(
  ... %>%
    count(...) %>%
    ...(...)
)
```


```{r include = FALSE}
# create artificial dataset where airport is not a key
```
```{r 61-create-artificial-dataset-where-airport-is-not-a-key}
dup_airports <-
  bind_rows(airports, sample_n(airports, 100))

dup_airports %>%
  count(faa)

dup_airports %>%
  count(faa) %>%
  count(n)

dup_airports %>%
  count(faa) %>%
  add_count(n) %>%
  filter(n > 1)
```


```{r include = FALSE}
# what happens if not key?
```
```{r 61-what-happens-if-not-key}
flights %>%
  left_join(dup_airports, by = c("dest" = "faa")) %>%
  select(origin, dest, name)

flights
```


```{r include = FALSE}
# Your turn: Is this combination a key? Why/why not?
```
```{r 61-your-turn-is-this-combination-a-key-why-why-not}
weather

weather %>%
  count(origin, year, month, day, hour) %>%
  count(n)
```


```{r include = FALSE}
# How to find the offenders?
```
```{r 61-how-to-find-the-offenders}
try(
  weather %>%
    count(...) %>%
    add_count(...) %>%
    filter(...)
)
```


```{r include = FALSE}
# Explain!
```
```{r 61-explain}

```


```{r include = FALSE}
# A novel approach: https://krlmlr.github.io/dm/
```
```{r 61-a-novel-approach-https-krlmlr-github-io-dm}

```


```{r include = FALSE}
##install.packages("devtools")
##devtools::install_github("krlmlr/dm")
```
```{r 61-install-packages-devtools}
NA
```
