# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
sudo: true
cache: packages
latex: false # didn't work with lualatex out of the box

addons:
  apt:
    packages:
      - lmodern
      - texlive-xetex
      - texlive-luatex
      - texlive-latex-recommended
      - texlive-math-extra

#before_install
before_install:
- R -q -e 'install.packages("remotes"); remotes::install_github("ropenscilabs/tic"); tic::prepare_all_stages()'

#install
install:
- R -q -e 'tic::install()'

#script
script:
- R -q -e 'tic::script()'

#deploy
deploy:
  provider: script
  script: R -q -e 'tic::deploy()'
  on:
    all_branches: true

#after_success
after_success:
- R -q -e 'tic::after_success()'
