---
title: "Select and rename"
author: "Kirill Müller"
date: "June 2, 2017"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(nycflights13)
```

## Select first five variables

```{r}
flights %>%
  select(..., ..., ..., ..., ...)
```

```{r}
flights %>%
  select(...:...)
```

```{r}
## Numeric indexes work, too

flights %>%
  select(...:...)
```


## Exclude the date

```{r}
flights %>%
  select(-..., -..., -...)
```

```{r}
flights %>%
  select(-...:-...)
```

```{r}
## Numeric indexes work, too

flights %>%
  select(-...:-...)
```

## Departure variables

```{r}
## starts_with()

flights %>% 
  select(...(...))
```


## Move departure variables to end

```{r}
## everything()

flights %>%
  select(-...(...), ...())
```

## Contour plot

```{r}
## Overriding label names

flights %>% 
  ggplot() +
  geom_bin2d(aes(dep_time, arr_time)) +
  xlab("Departure time") +
  ylab("Arrival time")
```


```{r}
## Renaming in the data

flights %>% 
  rename(`...` = ...) %>%
  rename(`...` = ...) %>%
  ggplot() +
  geom_contour(aes(..., ...)) +
  xlab() +
  ylab()
```

```{r}
## Use coord_fixed() for fixing axes
```

