---
title: "Arrange"
author: "Kirill Müller"
date: "June 2, 2017"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(nycflights13)
```


## Flight with shortest airtime

```{r}
flights %>% 
  arrange(air_time) %>%
  head(1)
```


## Flight with heaviest delay

```{r}
flights %>% 
  arrange(arr_delay) %>%
  tail(1)
```

Why doesn't this give the result we're looking for? Can we use a filter?

```{r}
flights %>% 
  filter(!is.na(arr_delay)) %>%
  arrange(arr_delay) %>%
  tail(1)
```

Or the pattern below?

```{r}
flights %>% 
  arrange(!is.na(arr_delay), arr_delay) %>%
  tail(1)
```

```{r}
flights %>% 
  arrange(-arr_delay) %>%
  head(1)
```

```{r}
flights %>% 
  arrange(desc(arr_delay)) %>%
  head(1)
```


# Flight with longest airtime

```{r}
flights %>% 
  arrange(desc(air_time)) %>%
  head(1)
```


# UA flights with lowest delay

```{r}
flights %>% 
  filter(carrier == "UA") %>% 
  arrange(arr_delay)
```


```{r}
flights %>% 
  arrange(arr_delay) %>% 
  filter(carrier == "UA")
```


# Recovering delay

```{r}
flights %>% 
  arrange(dep_delay - arr_delay)
```
