---
title: "rmarkdown exercises"
author: "Kirill Müller"
date: "October 18, 2017"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
library(tidyverse)
```

## [R + markdown](rmarkdown.html)

1. Choose "File → New File → R Markdown...". In the dialog, choose a document title and adapt the author name if necessary.

1. Choose "File → Knit document", or press Ctrl + Shift + K, or hit the "Knit" button at the top of the text pane.

1. Run all chunks in the document via Ctrl + Alt + R or "Code → Run region → Run All" or via the "Run" popup at the top of the text pane.

1. Run a single chunk by moving the caret in the text pane into the chunk and pressing Ctrl + Shift + Enter.

1. Navigate chunks and headers by choosing from the popup at the bottom or from the document outline (you may need to hit the "Show document outline" button at the top right, or press Ctrl + Shift + O).

1. Clear the entire document except the "YAML header" (the first few lines that start and end with `---`) and the setup chunk.

1. In this chunk, load the tidyverse package. Knit the resulting document. Does the result surprise you?

1. Insert a chunk via "Code → Insert chunk", Ctrl + Alt + I, or the "Insert" popup at the top of the text pane.

1. In this new chunk, show the `mpg` dataset.

1. In another new chunk, show a simple plot of the `mpg` dataset.

1. Add a descriptive text, use Markdown formatting (headers, emphasis, links, ...) and perhaps try an equation in LaTeX notation.

1. In this descriptive text, add a value computed from the data, e.g. `nrow(mtcars)`, as inline code.


## Slides and reports

1. Install the "xaringan", "rticles", and "bookdown" packages.

    Hint: Use `install.packages()`.

1. Choose File / New File / R Markdown... from the RStudio menu, in the dialog select "Ninja presentation" to create an example slide deck.

1. What templates were installed with "rticles"?

1. Navigate to https://github.com/rstudio/bookdown-demo (or search for "bookdown demo" in a search engine). Extract the demo to a directory of your choice, and follow the instructions in the `README.md` file.


## [RMarkdown workflow](https://github.com/krlmlr/vistransrep/tree/master/rmarkdown-example)

1. In your project, create two directories: `R` and `reports`

1. Create a script `prepare.R` in the `R` directory

1. Create an RMarkdown document from template, save it as `final.Rmd` in the `reports` directory.

1. Add code to `prepare.R` to transform the `flights` data in some way. (Use subsetting, add new variables, or compute a summary. Anything works.) Assign the result to a global variable using `<-`. Save this variable to a file using the `saveRDS()` function.

    Hint: Use `library(here)` and `here()` to control where the file is saved.

1. Leave only the header and the "setup" chunk in `final.Rmd`. In the "setup" chunk, insert a call to the `readRDS()` function for the file you saved in the previous step.

    Hint: Use `here` again, you should be using the same file name that you have used for `saveRDS()`.

1. Knit the document. This should work without failure (but show an empty document).

1. Create a second code chunk that shows a plot of your transformed data. Do not refer to `flights`. Knit again.
