---
title: "dplyr exercises"
author: "Kirill Müller"
date: "June 2, 2017"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
library(tidyverse)
```

## Filtering

1. View the `flights` dataset in RStudio's data pane. Look up the meaning of the variables in the help.

    Hint: You need to load the `nycflights13` package.

1. Find all flights that departed today four years ago.

1. Find all flights that departed between 8:00 AM and 10:00 PM.

1. Find all flights that departed in the three winter months.

1. Are there any flights where departure time is later than arrival time? What does this mean?

1. Find more exercises in item 1 of Section 5.2.4 of r4ds.


## Assignment, the pipe

1. View all flights that arrived after 10:00 PM. Use a combined filter, an intermediate variable, a nested expression, and the pipe. Which appeals more to you?

1. Extend the four solutions to view all `"UA"` flights that arrived after 10:00 PM.

1. Extend the four solutions to view all `"UA"` flights that departed before 6:00 AM and arrived after 10:00 PM.

1. Extend the four solutions to view all `"UA"` flights that departed before 6:00 AM and arrived after 10:00 PM and had a delay of more than two hours.

1. Extend the four solutions to view all `"UA"` flights that departed before 6:00 AM and arrived after 10:00 PM and had a delay of more than two hours, originating in one of New York City's airports.

1. Extend the four solutions to view all `"UA"` flights that departed before 6:00 AM and arrived after 10:00 PM and had a delay of more than two hours, originating in one of New York City's airports but excluding Honolulu International airport.

    Hint: Consult the `airports` dataset.

1. Apply more restrictions to the four solutions.


## Logical operators, NA

1. Find all flights that departed today four years ago, flown by `"US"`. Two simple solutions exist, which appeals most to you?

1. Find all flights that departed before 6:00 AM or after 10:00 PM.

1. Find all flights not flown by either `"UA"` or `"WN"`. Which of the three straightforward solutions appeal more to you?

1. Which flights have a missing departure or arrival time? Which have both missing? Can the number of flights that have a missing arrival but not departure time correspond to lost or crashed flights?

1. Find more exercises in item 4 of Section 5.2.4 of r4ds.


## Filtering and plotting

1. Plot a histogram of the air time of all flights. Exclude Honolulu International Airport in Hawaii to get rid of the peak at the right-hand side. Zoom into the flights that have an air time between 400 and 500 minutes.

    Hint: Start with `flights %>% ggplot() + ...`

1. Plot a heat map for all relations with an air time shorter than one hour.

    Hint: Use `geom_bin2d()`.

1. Think of other plots of the `flights` data that would not work if applied on the full dataset but are useful when applying a filter beforehand.


## Arrange

1. On what day did the flight with the shortest airtime take place?

    Hint: Use `head()` to restrict your result to one row only.

1. Which flights had the heaviest delays? Can you use the `tail()` verb to obtain this information?

1. On what day did the flight with the longest airtime take place?

1. Find two equivalent ways to select the six `"UA"` flights with the lowest delay. Which is faster? Why?

    Hint: RStudio has shortcuts for swapping the current line with the next or previous line.

1. Which flights were best in recovering from delay in the air?

1. Find more exercises in Section 5.3.1 of r4ds.


## Select and rename

1. Find three ways to select the first five variables from the `flights` dataset.

1. Find three ways to exclude the date of the flight.

1. Select all variables related to departure.

1. Move the variables related to scheduled time to the end of the table.

1. Create a contour plot of departure and arrival time. Use two different techniques to set pretty axis labels. Then, restrict the plot to all flights that arrive before 5:00 AM. How do you fix the aspect ratio of the plot?

    Hint: Use `geom_contour()`

1. Find more exercises in Section 5.4.1 of r4ds.


## Mutate

1. Store the speed for each flight as miles per hour in a new variable. Visualize the speed distribution as a histogram. Would this visualization work without involving `mutate()`?

1. Can you detect a difference in the speed distributions of on-time vs. delayed flights? Create a new variable that displays nicely in the legend or in the facet.

1. Visualize the deviation from the average departure delay for the three airports of New York City. Consider using a violin plot.

1. Find more exercises in Section 5.5.2 of r4ds.


## Summarize

1. Compute the mean arrival and departure delay overall, and per origin airport. What is the standard deviation of these variables? What is New York City's busiest airport?

1. Which carriers had the longest accumulated air time? Plot a bar chart with a suitable unit for the total time.

    Hint: Use `factor()` to fix the ordering of a categorical variable before plotting.

1. Which carriers specialize on long-distance routes? Plot a bar chart similar to the previous exercise.

1. Which plane had the most failed departure attempts?

1. Compute the ratio of short-distance routes (less than 300 miles) for each airline.

1. Find more exercises in item 1 of Section 5.6.7 of r4ds.


## Summarize with multiple variables

1. Which destination airport is serviced by the largest number of distinct carriers? Find a solution using `summarize()`, and one using `count()`. Which is more elegant?

1. Create a heat map for the share of cancelled flights per month per airline.

    Hint: Use `geom_raster()`

1. Find more exercises in Section 5.6.7 of r4ds.


## Grouped mutate

1. Which month is busiest in terms of miles flown? Draw a heat map to see if this pattern holds across all airlines.

1. Compute the ground time for each airplane on any given day. Make sure that you add only positive numbers. Visualize the distribution of ground times by airline.

1. Find more exercises in Section 5.7.1 of r4ds.


## Slides and reports

1. Install the "xaringan", "rticles", and "bookdown" packages.

    Hint: Use `install.packages()`.

1. Choose File / New File / R Markdown... from the RStudio menu, in the dialog select "Ninja presentation" to create an example slide deck.

1. What templates were installed with "rticles"?

1. Navigate to https://github.com/rstudio/bookdown-demo (or search for "bookdown demo" in a search engine). Extract the demo to a directory of your choice, and follow the instructions in the `README.md` file.


## RMarkdown workflow

1. In your project, create two directories: `R` and `reports`

1. Create a script `prepare.R` in the `R` directory

1. Create an RMarkdown document from template, save it as `final.Rmd` in the `reports` directory.

1. Add code to `prepare.R` to transform the `mpg` data in some way. (Use subsetting, add new variables, or compute a summary. Anything works.) Assign the result to a global variable using `<-`. Save this variable to a file using the `saveRDS()` function.

    Hint: Use `library(here)` and `here()` to control where the file is saved.

1. Leave only the header and the "setup" chunk in `final.Rmd`. In the "setup" chunk, insert a call to the `readRDS()` function for the file you saved in the previous step.

    Hint: Use `here` again, you should be using the same file name that you have used for `saveRDS()`.

1. Knit the document. This should work without failure (but show an empty document).

1. Create a second code chunk that shows a plot of your transformed data. Do not refer to `mpg`. Knit again.

    Hint: You can hide `mpg` from view by adding `mpg <- NULL` to the "setup" chunk.
...




## Spreading and gathering

1. Use `spread()` to convert `table2` to `table1`. What is the meaning of the `key` and `value` arguments?

1. Use `gather()` to convert `table1` to `table2`. Do you need an extra transformation to make the result fully identical? Can you reuse `key` and `value` from the previous result?

1. Use a bar chart to visualise the data. Which of `table1` or `table2` is more suitable for plotting?

1. Use `gather()` to convert `table4a` and `table4b` to `table2`.

    Hint: Use `bind_rows()` to combine similar tibbles.

1. Create a scatterplot that shows both highway and city fuel economy from the `mpg` dataset with two different colors using only one `geom_point()` call.

1. Find more exercises in Section 12.3.3 of r4ds.


## Separating and uniting

1. Convert `table3` to `table1` and `table2`.

1. Convert `table2` to `table3`.

1. Use `separate()` to compute departure and arrival hours and minutes in the `flights` dataset.

1. Find more exercises in Section 12.4.3 of r4ds.


## Keys and mutating joins

1. Do you see a problem in the `presidential` dataset? Can you see how does this affect the following bar plot without actually running the code?

    ```
    presidential %>%
      mutate(term = end - start) %>%
      ggplot() +
      geom_bar(aes(name, term))
    ```

1. How are the `flights`, `carriers`, and `airports` datasets connected? Which are primary, which are foreign keys?

    Hint: Use `count()` to support your hypothesis.

1. Plot a heat map of destination by airline for all flights shorter than 300 miles. Use explicit names for the carriers and the destinations. Does the result change if you use a full join? Do you use `geom_raster()` or `geom_bin2d()`?

    Hint: Use `by = c("dest" = "faa")`.

1. Find more exercises in Section 13.4.6 of r4ds.


## Filtering joins

1. Find the airports that are serviced by at least one flight. Which airports did not have direct connections in 2013?

1. Find more exercises in Section 13.5.1 of r4ds.


## Case study

1. Use your own data to answer a question about it using the tools you have learned in this course.

    Hint: To import, use the "readr" (CSV), "readxl" (Excel), or "haven" (SPSS/SAS/Stata) packages. Use the internet to find out how to import other kinds of data, use `as_tibble()` right after importing to get consistent printing.

1. Alternatively, create a plot of the total number of tuberculosis cases per year for eight countries of your choice. Can you also plot the share (relative to the overall population of the country)?
