---
title: "Logical operators and NA"
author: "Kirill Müller"
date: "June 2, 2017"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(nycflights13)
```


## Today's flights

```{r}
flights %>%
  filter((month = 6) & (day = 2))
```

```{r}
flights %>%
  filter(month = 6, day = 2)
```

Using a variable to define the date:

```{r}
current_month <- 6
current_day <- 2
flights %>%
  filter(month = current_month, day = current_day)
```

Beware of name collisions! The following does not compute what we're looking for:

```{r}
month <- 6
day <- 2
flights %>%
  filter(month = month, day = day)
```


## Inconvenient flights

```{r}
## Logical OR: |

flights %>% 
  filter(dep_time < 600 | dep_time >= 2200)
```

## Flown by other airline than UA or WN


```{r}
## Logical NOT and OR: ! |

flights %>% 
  filter(!(carrier == "UA" | carrier == "WN"))
```


```{r}
## Logical NOT and %in%

flights %>% 
  filter(!(carrier %in% c("UA", "WN")))
```


```{r}
## Logical AND: &

flights %>%
  filter(carrier != "UA" & carrier != "WN")
```


```{r}
flights %>% 
  filter(carrier != "UA") %>% 
  filter(carrier != "WN")
```

## Missing departure or arrival time

```{r}
## is.na()

flights %>% 
  filter(is.na(dep_time))
```

```{r}
## is.na()

flights %>% 
  filter(is.na(arr_time))
```

```{r}
## is.na()

flights %>% 
  filter(is.na(dep_time) | is.na(arr_time))
```

```{r}
## is.na()

flights %>% 
  filter(!is.na(dep_time) & is.na(arr_time))
```

I don't think we had hundreds of plane crashes in 2013.
