---
title: "Summarize"
author: "Kirill Müller"
date: "June 2, 2017"
output: html_document
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(nycflights13)
```

## Useful summary functions

- `sum()`, `prod()`
- `mean()`, `median()`
- `sd()`, `IQR()`, `mad()`
- `min()`, `quantile()`, `max()`
- `n()`
- `sum()` and `mean()` for logical variables
- `first()`, `last()`, `nth()`

Don't forget `na.rm = TRUE` if needed!


## Mean arrival and dep delay

```{r}
flights %>%
  summarize(mean(arr_delay, na.rm = ...))
```

```{r}
flights %>%
  summarize(mean(..., na.rm = ...))
```

```{r}
flights %>%
  summarize(
    mean(arr_delay, na.rm = ...),
    mean(dep_delay, na.rm = ...)
  )
```


```{r}
flights %>%
  group_by(...) %>% 
  summarize(...) %>% 
  ungroup
```

# Air time by carrier

```{r}
total_airtime_by_carrier <-
  flights %>% 
    group_by(...) %>% 
    summarize(acc_air_time = ...(air_time, ...)) %>% 
    ungroup

total_airtime_by_carrier
```

```{r}
total_airtime_by_carrier %>% 
  arrange(...) %>%
  ggplot() +
  geom_col(aes(factor(...), ...))
```

## Carriers for long-distance routes

```{r}
carrier_arranged_by_total_distance <-
  flights %>% 
    group_by(...) %>% 
    summarize(...) %>% 
    ungroup %>% 
    ...()

carrier_arranged_by_total_distance
```

```{r}
total_distance_by_carrier %>% 
  ggplot() +
  geom_col(aes(factor(...), ...))
```


## Worst plane

```{r}
flights %>% 
  filter(...(dep_time)) %>%
  group_by(...) %>% 
  summarize(...) %>% 
  ungroup()
```

```{r}
flights %>% 
  filter(...(dep_time)) %>%
  ...(...)
```


## Short-distance routes per airline

```{r}
flights %>%
  group_by(...) %>% 
  summarize(ratio = mean(...)) %>% 
  ungroup
```

