---
title: "Trend data"
author: "Kirill Müller"
date: "October 20, 2017"
output: html_document
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(nycflights13)
```


## Assignment 1

```{r cache = TRUE}
library(gfdata)
all_stats %>% 
  filter(five_regions == "High Impact Asia") %>% 
  ggplot(aes(x = year, y = hiv_new_infections_number)) +
  geom_line() +
  facet_wrap(~country, scales = "free_y")

all_stats %>%
  filter(five_regions == "High Impact Asia") %>%
  ggplot(aes(x = year, y = tb_new_cases_number)) +
  geom_line() +
  facet_wrap(~country, scales = "free_y")

all_stats %>%
  filter(five_regions == "High Impact Asia") %>%
  ggplot(aes(x = year, y = malaria_new_cases_number)) +
  geom_line() +
  facet_wrap(~country, scales = "free_y")
```

## Assignment 2

```{r cache = TRUE, fig.height = 8}
library(gfdata)
all_stats_new_cases_long <- 
  all_stats %>%
  rename(hiv_new_cases_number = hiv_new_infections_number) %>%
  select(
    five_regions, country, year,
    ends_with("_new_cases_number")
  ) %>% 
  gather(indicator, count, -five_regions, -country, -year) %>% 
  separate(
    indicator,
    into = c("disease", "indicator"),
    extra = "merge"
  ) %>%
  mutate(disease = recode(
    disease,
    "tb" = "TB", "malaria" = "Malaria", "hiv" = "HIV"
  )) %>% 
  mutate(disease = forcats::fct_inorder(disease)) %>% 
  spread(indicator, count)

all_stats_new_cases_long
```

```{r cache = TRUE, fig.height = 8}
all_stats_new_cases_long %>% 
  filter(five_regions == "High Impact Asia") %>% 
  ggplot(aes(x = year, y = new_cases_number)) +
  geom_line() +
  facet_grid(country~disease, scales = "free")
```

## Assignment 3

```{r cache = TRUE}
library(gfdata)
all_stats_new_cases_long %>% 
  group_by(five_regions, year, disease) %>% 
  summarize(new_cases_number = sum(new_cases_number, na.rm = TRUE)) %>% 
  ungroup() %>% 
  ggplot(aes(x = year, y = new_cases_number)) +
  geom_line() +
  facet_grid(five_regions~disease, scales = "free")
```

## Assignment 4

```{r}
library(gfdata)
all_stats_inc_mort_long <-
  all_stats %>%
  rename(hiv_new_cases_number = hiv_new_infections_number) %>%
  rename(hiv_deaths_number = aids_deaths_number) %>%
  group_by(five_regions, country) %>%
  mutate(lag_population_excluding_plwha = lag(population_excluding_plwha) * 100) %>%
  ungroup() %>%
  transmute(
    five_regions, country, year,
    nominator_hiv_incidence = hiv_new_cases_number * 100,
    denominator_hiv_incidence = lag_population_excluding_plwha,
    nominator_hiv_mortality = hiv_deaths_number * 100,
    denominator_hiv_mortality = population_all_ages,
    nominator_tb_incidence = tb_new_cases_number * 100000,
    denominator_tb_incidence = population_all_ages,
    nominator_tb_mortality = tb_deaths_number * 100000,
    denominator_tb_mortality = population_all_ages,
    nominator_malaria_incidence = malaria_new_cases_number * 1000,
    denominator_malaria_incidence = population_at_malaria_risk,
    nominator_malaria_mortality = malaria_deaths_number * 1000,
    denominator_malaria_mortality = population_at_malaria_risk
  ) %>%
  gather(indicator, value, -five_regions, -country, -year) %>%
  separate(
    indicator,
    into = c("nom_denom", "indicator"),
    extra = "merge"
  ) %>%
  mutate(nom_denom = forcats::fct_inorder(nom_denom)) %>%
  separate(
    indicator,
    into = c("disease", "indicator"),
    extra = "merge"
  ) %>%
  mutate(disease = recode(
    disease,
    "tb" = "TB", "malaria" = "Malaria", "hiv" = "HIV"
  )) %>% 
  mutate(disease = forcats::fct_inorder(disease)) %>%
  spread(nom_denom, value) %>%
  filter(nominator > 0 & denominator > 0)

all_stats_inc_mort_long
```

```{r cache = TRUE, fig.height = 8}
all_stats_inc_mort_long %>%
  filter(five_regions == "High Impact Asia") %>%
  filter(indicator == "mortality") %>%
  transmute(
    country, year, disease, indicator,
    rate = nominator / denominator
  ) %>%
  spread(indicator, rate) %>%
  ggplot(aes(x = year, y = mortality)) +
  geom_line() +
  scale_y_continuous(limits = c(0, NA)) +
  facet_wrap(
    ~country + disease,
    scales = "free",
    ncol = 3,
    labeller = labeller(.multi_line = FALSE)
  )
```

## Assignment 5

```{r cache = TRUE, fig.height = 8}
all_stats_inc_mort_long %>%
  group_by(five_regions, disease, indicator, year) %>%
  summarise(
    rate = sum(nominator) / sum(denominator)
  ) %>%
  spread(indicator, rate) %>%
  ggplot(aes(x = year, y = mortality)) +
  geom_line() +
  scale_y_continuous(limits = c(0, NA)) +
  facet_wrap(
    ~five_regions + disease,
    scales = "free",
    ncol = 3,
    labeller = labeller(.multi_line = FALSE)
  )
```

## Assignment 6


```{r cache = TRUE, fig.height = 8}
all_stats_inc_mort_long %>%
  group_by(five_regions, disease, indicator, year) %>%
  summarise(
    rate = sum(nominator) / sum(denominator)
  ) %>%
  mutate(rate_change = rate / first(rate)) %>%
  select(-rate) %>%
  ungroup() %>%
  spread(indicator, rate_change) %>%
  ggplot(aes(x = year, y = mortality)) +
  geom_line() +
  facet_grid(five_regions ~ disease)
```


## Assignment 7

```{r fig.height = 8}
all_stats %>%
  select(
    five_regions, country, year,
    people_living_with_hiv_aids_number,
    people_living_with_hiv_aids_lower_number,
    people_living_with_hiv_aids_higher_number
  ) %>%
  filter(grepl("^High Impact ", five_regions)) %>%
  ggplot(aes(x = year)) +
  geom_ribbon(
    aes(
      ymin = people_living_with_hiv_aids_lower_number,
      ymax = people_living_with_hiv_aids_higher_number
    ),
    fill = "grey"
  ) +
  geom_line(
    aes(
      y = people_living_with_hiv_aids_number
    ),
    color = "green"
  ) +
  scale_y_continuous(limits = c(0, NA)) +
  facet_wrap(~country, scales = "free_y")
```


## Assignment 8

```{r fig.height = 8}
all_stats %>%
  select(
    five_regions, country, year,
    people_living_with_hiv_aids_number,
    people_living_with_hiv_aids_lower_number,
    people_living_with_hiv_aids_higher_number
  ) %>%
  group_by(five_regions, year) %>%
  summarize_at(
    vars(starts_with("people_living_with_hiv_aids_")),
    funs(sum(., na.rm = TRUE))
  ) %>%
  ungroup() %>%
  ggplot(aes(x = year)) +
  geom_ribbon(
    aes(
      ymin = people_living_with_hiv_aids_lower_number,
      ymax = people_living_with_hiv_aids_higher_number
    ),
    fill = "grey"
  ) +
  geom_line(
    aes(
      y = people_living_with_hiv_aids_number
    ),
    color = "green"
  ) +
  scale_y_continuous(limits = c(0, NA)) +
  facet_wrap(~five_regions, scales = "free_y")
```



## Assignment 9

```{r}
library(gfdata)
eligibility <-
  all_stats %>%
  select(
    five_regions, country, year,
    ends_with("_eligible")
  ) %>%
  gather(disease, eligible, -five_regions, -country, -year) %>%
  separate(disease, into = c("disease"), extra = "drop")

deaths <-
  all_stats %>%
  select(
    five_regions, country, year,
    hiv_deaths_number = aids_deaths_number,
    ends_with("_deaths_number")
  ) %>%
  gather(disease, deaths_number, -five_regions, -country, -year) %>%
  separate(disease, into = c("disease"), extra = "drop")

eligibility %>%
  left_join(deaths, by = c("five_regions", "country", "year", "disease")) %>%
  group_by(year, disease, eligible) %>%
  summarize(deaths_number = sum(deaths_number, na.rm = TRUE)) %>%
  mutate(deaths_share = deaths_number / sum(deaths_number, na.rm = TRUE)) %>%
  select(-deaths_number) %>%
  ungroup() %>%
  filter(eligible != "Yes") %>%
  filter(year <= 2015) %>%
  ggplot(aes(disease, deaths_share, fill = eligible)) +
  geom_col() +
  scale_y_continuous(labels = scales::percent) +
  facet_wrap(~year)
```
