---
title: "dplyr exercises part 1"
author: "Kirill Müller"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
library(tidyverse)
library(nycflights13)
knitr::opts_chunk$set(cache = TRUE)
```

## [Filtering](filtering.html)

1. View the `flights` dataset in RStudio's data pane. Look up the meaning of the variables in the help.

    Hint: You need to load the `nycflights13` package.
    
    ```r
    View(___)
    ```

1. Find all flights that departed between 8:00 AM and 10:00 PM.

    ```r
    flights %>%
      filter(between(dep_time, ___, ___))
    ```

1. Find all flights that departed in the three winter months.

    ```r
    flights %>%
      filter(month ___ c(___)))
    ```

1. Are there any flights where departure time is later than arrival time? What does this mean?

    ```r
    flights %>%
      filter(_____)
    ```

1. Find all flights that departed today four years ago.

    ```r
    flights %>%
      filter(month ___, day ___)
    ```

## [Arrange](arrange.html)

1. On what day did the flight with the shortest airtime take place?

    Hint: Use `head()` to restrict your result to one row only.

    ```r
    flights %>% 
      arrange(___) %>%
      head(1)
    ```

1. Which flights had the heaviest delays? Can you use the `tail()` verb to obtain this information?

    ```r
    flights %>% 
      arrange(___) %>%
      tail(1)

    flights %>% 
      arrange(desc(___)) %>%
      ___(1)
    ```

1. On what day did the flight with the longest airtime take place?

    ```r
    flights %>% 
      arrange(___ - ___) %>%
      head(1)
    ```

1. Find two equivalent ways to select the six `"UA"` flights with the lowest delay. Which is faster? Why?

    Hint: RStudio has shortcuts for swapping the current line with the next or previous line.

    ```r
    flights %>%
      filter(___) %>%
      arrange(___)

    flights %>%
      arrange(___) %>%
      filter(___)
    ```

1. Which flights were best in recovering from delay in the air?

## [Assignment, the pipe](pipe.html)

1. View all flights that arrived after 10:00 PM. Use an intermediate variable, a nested expression, and the pipe. Which appeals more to you?

    ```r
    flights_after_10 <- filter(flights, ___)
    View(flights_after_10)
    ```

    ```r
    View(filter(flights, ___))
    ```

    ```r
    flights %>%
      filter(___) %>%
      View()
    ```

1. Extend the four solutions to view all `"UA"` flights that arrived after 10:00 PM.

    ```r
    flights_after_10 <- filter(flights, ___)
    ua_flights_after_10 <- ...
    View(___)
    ```

    ```r
    View(filter(filter(flights, ___)))
    ```

    ```r
    flights %>%
      filter(___) %>%
      filter(___) %>%
      View()
    ```

1. Extend the four solutions to view all `"UA"` flights that departed before 6:00 AM and arrived after 10:00 PM.

1. Extend the four solutions to view all `"UA"` flights that departed before 6:00 AM and arrived after 10:00 PM and had a delay of more than two hours.

1. Extend the four solutions to view all `"UA"` flights that departed before 6:00 AM and arrived after 10:00 PM and had a delay of more than two hours, originating in one of New York City's airports.

1. Extend the four solutions to view all `"UA"` flights that departed before 6:00 AM and arrived after 10:00 PM and had a delay of more than two hours, originating in one of New York City's airports but excluding Honolulu International airport.

    Hint: Consult the `airports` dataset, use a filter with the predicate `stringr::str_detect(name, "^Honolulu")` .

1. Sort the result by `distance`.


## [Filtering and plotting](filter-plot.html)

1. Plot a histogram of the air time of all flights. Exclude Honolulu International Airport in Hawaii to get rid of the peak at the right-hand side. Zoom into the flights that have an air time between 400 and 500 minutes.

    Hint: Start with `flights %>% ggplot() + ...`
    
    ```r
    flights %>% 
      ggplot(___) +
        ___()

    flights %>% 
      filter(___) %>%
      ggplot(___) +
        ___()

    flights %>% 
      filter(___) %>%
      filter(___) %>%
      ___
    ```

1. Plot a heat map for all relations with an air time shorter than one hour.

    Hint: Use `geom_bin2d()`.
    
    ```r
    flights %>% 
      filter(___) %>%
      ggplot(___) +
        ___()
    ```


1. Think of other plots of the `flights` data that would not work if applied on the full dataset but are useful when applying a filter beforehand.

## [Combining filters](filter-combine.html)

1. Look at the "Details" section in the help page for `|` with `help("|")` to understand predicate logic in R. (We need element-wise comparisons.)

1. Find all flights that departed today x years ago, flown by `"US"`. Two simple solutions exist, which appeals most to you?

    ```r
    flights %>%
      filter(___, ___) %>%
      filter(___)
      
    flights %>%
      filter(_____)
    ```  

1. Find all flights that departed before 6:00 AM or after 10:00 PM.

    ```r
    flights %>%
      filter(___ | ___)
    ```

1. Find all flights not flown by either `"UA"` or `"WN"`. Can you think of three different solutions? Which appeals more to you?

    ```r
    flights %>%
      filter(___ ___ ___)

    flights %>%
      filter(!(___) ___ !(___))

    flights %>%
      filter(!(_____))
    ```

1. Which flights have a missing departure or arrival time? Which have both missing? Can the number of flights that have a missing arrival but not departure time correspond to lost or crashed flights?

    ```r
    flights %>%
      filter(is.na(___))

    flights %>%
      filter(___(___) ___ _____)

    flights %>%
      filter(_____ ___ !_____)
    ```

1. Find two equivalent ways to select the six `"UA"` flights with the lowest delay. Which is faster? Why?

    Hint: RStudio has shortcuts for swapping the current line with the next or previous line.

    ```r
    flights %>%
      filter(___) %>%
      arrange(___)

    flights %>%
      arrange(___) %>%
      filter(___)
    ```

1. Find more exercises in items 1 and 4 of Section 5.2.4, and in Section 5.3.1, of r4ds.


## [Select and rename](select-rename.html)

1. Find three ways to select the first five variables from the `flights` dataset.

    ```r
    flights %>% 
      select(___, ___, ________)

    flights %>% 
      select(___:___)

    flights %>% 
      select(___:___)
    ```


1. Find three ways to exclude the date of the flight.

    ```r
    flights %>% 
      select(___, ___, ______________________)

    flights %>% 
      select(-___, -___, -___)

    flights %>% 
      select(-___:-___)
    ```

1. Select all variables related to departure.

    ```r
    flights %>% 
      select(___, ___, _______)

    flights %>% 
      select(starts_with("___"))
    ```

1. Move the variables related to scheduled time to the end of the table.

    ```r
    flights %>% 
      select(-___, -___, _______, everything(), ___, ___)
    ```

1. Create a contour plot of departure and arrival time. Rename the columns to show prettily in the plot. Restrict the plot to all flights that arrive before 5:00 AM.

    ```r
    flights %>%
      select(`___` = ___, `___` = ___, ___) %>%
      filter(___) %>%
      ggplot(aes(x = `___`, y = `___`)) +
      geom_density2d()
    ```

1. Find more exercises in Section 5.4.1 of r4ds.


## [Mutate](mutate.html)

1. Store the speed for each flight as miles per hour in a new variable.

    ```r
    flights %>% 
      mutate(miles_per_hour = air_time ___ distance ___ ___) %>%
      ggplot(aes(___)) +
      _____
    ```
    
1. Can you use an intermediate variable to clarify the intent? How do you remove the intermediate variable?

    ```r
    flights %>% 
      mutate(miles_per_minute = _____) %>% 
      mutate(miles_per_hour = _____) %>% 
      select(_____)
    ```
    
1. Visualize the speed distribution as a histogram. Would this visualization work without involving `mutate()`?

    ```r
    flights %>% 
      ______ %>%
      ggplot(aes(___)) +
      _____

    # Alternative:
    flights %>%
      ggplot(aes(___)) +
      _____
    ```

1. Create a new logical variable that indicates if the flight arrived on time.

    ```r
    flights %>%
      mutate(on_time = (___ <= 0))
    ```

1. Visualize the aggregated on-time status per airline with a useful text.

    ```r
    flights %>%
      flights %>%
      mutate(
        on_time = _____,
        on_time_desc = if_else(___, "On time", ___)
      ) %>%
      ggplot(aes(___)) +
      geom_bar()
    ```

1. Can you detect a difference in the speed distributions of on-time vs. delayed flights? Ose color of faceting.

    ```r
    speed_and_on_time_info <-
      _____

    speed_and_on_time_info %>%
      ggplot() +
      geom_freqpoly(
        aes(x = ___, y = ..density.., color = ___),
        na.rm = TRUE,
        binwidth = 20
      )

    speed_and_on_time_info %>%
      ggplot() +
      geom_histogram(
        aes(x = ___),
        na.rm = TRUE,
        binwidth = 20
      ) +
      facet_wrap(~___, ncol = 1)
    ```

1. Create two new variables `date_hour` and `date_ymd`, using `as.Date()` or `lubridate::make_date()`, respectively. Are the two values the same for all observations? What happens if we omit the `tz` argument to `as.Date()`?

    ```r
    flights %>%
      mutate(
        ___ = as.Date(___, tz = "EST"),
        ___ = lubridate::make_date(_____)
      ) %>% 
      filter(___)
    ```

1. Visualize the deviation from the overall average departure delay for the three airports of New York City. Consider using a violin plot.

    ```r
    flights %>%
      mutate(dep_delay_dev = ___ - mean(___)) %>%
      ggplot(aes(___)) +
      _____ +
      _____
    ```

1. Find more exercises in Section 5.5.2 of r4ds.


## [Summarize](summarize.html)

1. Compute the mean arrival and departure delay overall, and per origin airport. What is the standard deviation of these variables? What is New York City's busiest airport?

    ```r
    flights %>%
      summarize(mean(___, na.rm = ___))

    flights %>%
      group_by(___) %>%
      summarize(___)

    flights %>%
      count(___) %>%
      arrange(___)
    ```

1. Which carriers had the longest accumulated air time, excluding cancelled flights?

    ```r
    flights %>%
      group_by(___) %>%
      summarize(acc_air_time = sum(_____)) %>% 
      ungroup()
    ```
    
1. Plot a bar chart of the accumulated air time per airline, with a suitable unit for the total time.

    Hint: Use `forcats::fct_inorder()` to fix the ordering of a categorical variable before plotting.

    ```r
    total_airtime_by_carrier <-
      _____
      
    total_airtime_by_carrier %>%
      arrange(acc_air_time) %>%
      mutate(carrier = forcats::fct_inorder(carrier)) %>%
      ggplot(aes(___)) +
        geom_col()
    ```
    
1. Which carriers specialize on long-distance routes?

    ```r
    flights
      _____ %>%
      _____ %>%
      _____ %>%
      arrange(___)
    ```

1. Plot a bar chart of median distance per flight. Do you use `geom_bar()` or `geom_col()`? Why?

    ```r
    median_miles_by_carrier <-
      _____ %>%
      _____ %>%
      _____

    median_miles_by_carrier %>%
      arrange(_____) %>%
      mutate(_____) %>%
      ggplot(aes(___)) +
        geom____()
    ```

1. Which plane had the most failed departure attempts? Can you find a solution without `filter()`?

    Hint: Use the idiom `sum(___)` to count the rows where a predicate is true.

    ```r
    flights %>%
      filter(is.na(dep_time)) %>%
      group_by(tailnum) %>%
      _____ %>%
      _____ %>%
      filter(!is.na(tailnum)) %>%
      arrange(desc(___)) %>% 
      head(1)

    # Alternative without filter():
    flights %>%
      group_by(tailnum) %>%
      _____ %>%
      _____ %>%
      arrange(_____) %>%
      head(1)
    ```

1. Compute the ratio of short-distance routes (less than 300 miles) for each airline.

    Hint: Use the idiom `mean(___)` to compute the share of rows where a predicate is true.

    ```r
    flights %>%
      group_by(carrier) %>%
      _____ %>% 
      ungroup()
    ```

1. Plot a bar chart of the ratio of short-distance routes.

    ```r
    short_distance_route_ratio <-
      _____

    short_distance_route_ratio %>%
      ggplot(aes(___)) +
        geom_col()
    ```

1. Find more exercises in item 1 of Section 5.6.7 of r4ds.


## [Summarize with multiple variables](summarize-mult.html)

1. Which relation is serviced by the largest number of distinct airlines? Find a solution using `summarize()`, one using `count()`, and one using `tally()`. Which is more elegant?

    ```r
    flights %>%
      group_by(___, ___, airline) %>%
      summarize(n = n()) %>%
      summarize(n_airlines = ___) %>%
      ungroup() %>%
      arrange(___) %>%
      head(1)

    flights %>%
      count(_____) %>%
      count(_____) %>%
      _____ %>%
      _____

    flights %>%
      group_by(_____) %>%
      tally() %>%
      tally(wt = NULL) %>%
      _____ %>%
      _____
    ```

1. Compute the share of cancelled flights per month per airline.

    ```r
    flights %>% 
      group_by(_____) %>% 
      summarize(share_of_cancelled = _____) %>%
      ungroup()
    ```

1. Create a heat map of cancelled flights.

    ```r
    cancelled_flights <-
      _____

    cancelled_flights %>% 
      ggplot() +
      geom_raster(
        aes(
          x = ___,
          y = factor(month),
          fill = ___
        )
      )
    ```

1. Find more exercises in Section 5.6.7 of r4ds.
