---
title: "dplyr exercises part 2"
author: "Kirill Müller"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
library(tidyverse)
knitr::opts_chunk$set(cache = TRUE)
```



## [Summarize](summarize.html)

1. Compute the mean arrival and departure delay overall, and per origin airport. What is the standard deviation of these variables? What is New York City's busiest airport?

    ```r
    flights %>%
      summarize(mean(___, na.rm = ___))

    flights %>%
      group_by(___) %>%
      summarize(___)

    flights %>%
      count(___) %>%
      arrange(___)
    ```

1. Which carriers had the longest accumulated air time, excluding cancelled flights?

    ```r
    flights %>%
      group_by(___) %>%
      summarize(acc_air_time = sum(_____)) %>% 
      ungroup()
    ```
    
1. Plot a bar chart of the accumulated air time per airline, with a suitable unit for the total time.

    Hint: Use `forcats::fct_inorder()` to fix the ordering of a categorical variable before plotting.

    ```r
    total_airtime_by_carrier <-
      _____
      
    total_airtime_by_carrier %>%
      arrange(acc_air_time) %>%
      mutate(carrier = forcats::fct_inorder(carrier)) %>%
      ggplot(aes(___)) +
        geom_col()
    ```
    
1. Which carriers specialize on long-distance routes?

    ```r
    flights
      _____ %>%
      _____ %>%
      _____ %>%
      arrange(___)
    ```

1. Plot a bar chart of median distance per flight. Do you use `geom_bar()` or `geom_col()`? Why?

    ```r
    median_miles_by_carrier <-
      _____ %>%
      _____ %>%
      _____

    median_miles_by_carrier %>%
      arrange(_____) %>%
      mutate(_____) %>%
      ggplot(aes(___)) +
        geom____()
    ```

1. Which plane had the most failed departure attempts? Can you find a solution without `filter()`?

    Hint: Use the idiom `sum(___)` to count the rows where a predicate is true.

    ```r
    flights %>%
      filter(is.na(dep_time)) %>%
      group_by(tailnum) %>%
      _____ %>%
      _____ %>%
      filter(!is.na(tailnum)) %>%
      arrange(desc(___)) %>% 
      head(1)

    # Alternative without filter():
    flights %>%
      group_by(tailnum) %>%
      _____ %>%
      _____ %>%
      arrange(_____) %>%
      head(1)
    ```

1. Compute the ratio of short-distance routes (less than 300 miles) for each airline.

    Hint: Use the idiom `mean(___)` to compute the share of rows where a predicate is true.

    ```r
    flights %>%
      group_by(carrier) %>%
      _____ %>% 
      ungroup()
    ```

1. Plot a bar chart of the ratio of short-distance routes.

    ```r
    short_distance_route_ratio <-
      _____

    short_distance_route_ratio %>%
      ggplot(aes(___)) +
        geom_col()
    ```

1. Find more exercises in item 1 of Section 5.6.7 of r4ds.


## [Summarize with multiple variables](summarize-mult.html)

1. Which relation is serviced by the largest number of distinct airlines? Find a solution using `summarize()`, one using `count()`, and one using `tally()`. Which is more elegant?

    ```r
    flights %>%
      group_by(___, ___, airline) %>%
      summarize(n = n()) %>%
      summarize(n_airlines = ___) %>%
      ungroup() %>%
      arrange(___) %>%
      head(1)

    flights %>%
      count(_____) %>%
      count(_____) %>%
      _____ %>%
      _____

    flights %>%
      group_by(_____) %>%
      tally() %>%
      tally(wt = NULL) %>%
      _____ %>%
      _____
    ```

1. Compute the share of cancelled flights per month per airline.

    ```r
    flights %>% 
      group_by(_____) %>% 
      summarize(share_of_cancelled = _____) %>%
      ungroup()
    ```

1. Create a heat map of cancelled flights.

    ```r
    cancelled_flights <-
      _____

    cancelled_flights %>% 
      ggplot() +
      geom_raster(
        aes(
          x = ___,
          y = factor(month),
          fill = ___
        )
      )
    ```

1. Find more exercises in Section 5.6.7 of r4ds.


## [Grouped mutate](window.html)

1. Which month is busiest in terms of miles flown, over all carriers?

    ```r
    flights %>%
      group_by(___) %>%
      mutate(total_distance = sum(___)) %>%
      mutate(month_share = ___ / ___) %>% 
      arrange(desc(month_share)) %>%
      slice(1)
    ```

1. Visualize with a bar chart.

1. Which month is busiest in terms of miles flown, per carrier?

    Hint: Compute the share of yearly miles flown of each airline in each month.

    ```r
    flights %>%
      group_by(___, ___) %>%
      summarize(total_distance_by_carrier = sum(distance)) %>%
      mutate(total_distance = sum(___)) %>%
      ungroup() %>%
      mutate(month_share_by_carrier = ___ / ___) %>% 
      arrange(month_share_by_carrier) %>% 
      group_by(___) %>%
      slice(1)
    ```
    
1. Draw a heat map of miles flown per month per airline to see if this pattern holds across all airlines.

    ```r
    monthly_shares <-
      _____
    
    monthly_shares %>%
      ggplot(aes(factor(month), ___, fill = ___)) +
      geom_tile() +
      scale_fill_continuous(trans = "log10")
    ```

1. Find more exercises in Section 5.7.1 of r4ds.
