---
title: "ggplot2 exercises part 3"
author: "Kirill Müller, cynkra GmbH"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
library(tidyverse)
knitr::opts_chunk$set(cache = TRUE)
```

## [Scales](scales.html)

1. Choose one or two of your previous plots, and give the scales a proper name.

    Hint: Use one or more `scale_...()` functions.
    
    ```
    ggplot(
      data = mpg,
      mapping = aes(x = displ, y = hwy, color = factor(year))
    ) +
      geom_point() +
      geom_smooth(method = "lm") +
      facet_wrap(~class) +
      scale_x_continuous(name = "___") +
      scale_y_continuous(name = "___") +
      scale_color_discrete(name = "___")
    ```

1. What happens if you call the same `scale_...()` function twice in a plot?

1. Add an overview over all available colorblind friendly Brewer scales to your rmarkdown document.

    Hint: Insert a code chunk containing `RColorBrewer::display.brewer.all(colorblindFriendly = TRUE)`

1. Choose an appealing scale for one of your plots that use the "color" or "fill" aesthetics. Apply it with `scale_..._brewer("<name>", palette = "<palette>")`

    Hint: Use `scale_..._distiller()` if you have mapped a continuous variable.

1. Practice Markdown: Create sections, subsections, item lists, emphasized and bold text, ... .


## [Coordinate systems](coord.html)

1. Create a flipped boxplot of fuel economy by transmission type.

1. Plot highway vs. city fuel economy with an additional `geom_abline()` layer.  How do you set a 45° degree for the diagonal line? 

1. Try to "estimate" an approximate ratio between the two economy measures by tweaking the `slope` argument to `geom_abline()`.


## [Theming](theme.html)

1. Choose your favorite among the predefined themes.

    Hint: All start with `theme_...()`, but watch out for `theme_set()`.

1. Apply `theme(legend.position = "bottom")` to a plot with a color or fill legend.  What happens if you then apply `theme_bw()`? Why?


## [plotly](plotly.html)

1. Convert one of the scatterplots you generated previously using the following pattern:

    ```
    p <-
      data %>% 
      ___ %>%
      ggplot(aes(___)) +
        geom_point()
    
    plotly::ggplotly(p)
    ```

1. Experiment with the plotly controls on the top right.

1. Add extra aesthetics to the scatterplot. Hover with the mouse over the points:

    ```
    p <-
      data %>% 
      ___ %>%
      ggplot(aes(___, extra1 = manufacturer, extra2 = model)) +
        geom_point()
    
    plotly::ggplotly(p)
    ```

1. Convert a bar plot or a histogram to plotly. How does this affect the tooltip?

1. See https://plotly-book.cpsievert.me/linking-views-without-shiny.html for examples of linking two plots, or linking plots with other widgets. This requires the _crosstalk_ package:

    ```
    install.packages("crosstalk")
    ```

## [leaflet](leaflet.html)

1. Show the `quakes` data, or a subset, on a map:

    ```
    library(leaflet)
    quakes %>% 
      ___ %>% 
      leaflet() %>% 
      addTiles() %>% 
      addCircles()
    ```

1. Add a popup to the tiles. Click on one of the circles

    Hint: Use `str_c()` or `paste0()` to concatenate text and data.
    
    ```
    library(leaflet)
    ___ %>% 
      addCircles()
    ```
    
1. Explore further options in `?addTiles`.

1. See section 4.2.3 in https://plotly-book.cpsievert.me/linking-views-without-shiny.html for linking a map to a plot.
