---
title: "Interactive maps"
author: "Kirill Müller, cynkra GmbH"
date: "November 30, 2018"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(nycflights13)
knitr::opts_chunk$set(cache = TRUE)
```

## A simple map

Show the `quakes` data, or a subset, on a map:

```
library(leaflet)
quakes %>% 
  ___ %>% 
  leaflet() %>% 
  addTiles() %>% 
  addCircles()
```

<details>
<summary>&#x25BA; Solution:</summary>
```{r leaflet-1}
library(leaflet)
quakes %>% 
  head(50) %>% 
  leaflet() %>% 
  addTiles() %>% 
  addCircles()
```
</details>

## A map with a tooltip

Add a popup to the tiles. Click on one of the circles

Hint: Use `str_c()` or `paste0()` to concatenate text and data.
    
```
library(leaflet)
___ %>% 
  addCircles()
```

<details>
<summary>&#x25BA; Solution:</summary>
```{r leaflet-2}
library(leaflet)
quakes %>% 
  head(50) %>% 
  leaflet() %>% 
  addTiles() %>% 
  addCircles(popup = ~str_c("Magnitude: ", mag))
```
</details>

## Other kinds of layer

Explore further options in `?addTiles`.

## More exercises

See section 4.2.3 in https://plotly-book.cpsievert.me/linking-views-without-shiny.html for linking a map to a plot.
