---
title: "Logical operators and NA"
author: "Kirill Müller"
date: "June 2, 2017"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(nycflights13)
knitr::opts_chunk$set(cache = TRUE)
```


## Today's flights, flown by "US"

```{r logical-1}
flights %>%
  filter((month == 6) & (day == 2) & (carrier == "US"))
```

```{r logical-2}
flights %>%
  filter(month == 6, day == 2, carrier == "US")
```


## Inconvenient flights

```{r logical-3}
## Logical OR: |

flights %>% 
  filter(dep_time < 600 | dep_time >= 2200)
```

## Flown by other airline than UA or WN


```{r logical-4}
## Logical NOT and OR: ! |

flights %>% 
  filter(!(carrier == "UA" | carrier == "WN"))
```


```{r logical-5}
## Logical NOT and %in%

flights %>% 
  filter(!(carrier %in% c("UA", "WN")))
```


```{r logical-6}
## Logical AND: &

flights %>%
  filter(carrier != "UA" & carrier != "WN")
```


```{r logical-7}
flights %>% 
  filter(carrier != "UA") %>% 
  filter(carrier != "WN")
```

## Missing departure or arrival time

```{r logical-8}
## is.na()

flights %>% 
  filter(is.na(dep_time))
```

```{r logical-9}
## is.na()

flights %>% 
  filter(is.na(arr_time))
```

```{r logical-10}
## is.na()

flights %>% 
  filter(is.na(dep_time) | is.na(arr_time))
```

```{r logical-11}
## is.na()

flights %>% 
  filter(!is.na(dep_time) & is.na(arr_time))
```

I don't think we had hundreds of plane crashes in 2013.
