---
title: "Mutate"
author: "Kirill Müller"
date: "June 2, 2017"
output: html_document
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(nycflights13)
knitr::opts_chunk$set(cache = TRUE)
```


## Speed as miles per hour

```{r mutate-1}
flights %>%
  mutate(miles_per_hour = distance / air_time * 60)
```

```{r mutate-1-1}
flights %>%
  mutate(miles_per_minute = distance / air_time) %>% 
  mutate(miles_per_hour = miles_per_minute * 60) %>% 
  select(-miles_per_minute)
```

```{r mutate-1-2}
flights %>%
  mutate(miles_per_hour = distance / air_time * 60) %>%
  ggplot() +
  geom_histogram(
    aes(miles_per_hour),
    na.rm = TRUE,
    binwidth = 20
  )
```


```{r mutate-1-3}
flights %>% 
  ggplot() +
  geom_histogram(aes(distance / air_time))
```

## On time status

```{r mutate-1-bis}
flights %>%
  mutate(
    on_time = (arr_delay <= 0),
    on_time_desc = if_else(on_time, "On time", "Delayed")
  )
```


```{r mutate-1-bis-1}
flights %>%
  mutate(
    on_time = (arr_delay <= 0),
    on_time_desc = if_else(on_time, "On time", "Delayed")
  ) %>%
  ggplot(aes(x = carrier, fill = on_time_desc)) +
  geom_bar()
```



## Speed distributions

```{r mutate-3}
speed_and_on_time_info <-
  flights %>%
  mutate(
    miles_per_minute = distance / air_time,
    miles_per_hour = miles_per_minute * 60
  ) %>% 
  select(-miles_per_minute) %>% 
  mutate(
    on_time = (arr_delay <= 0),
    on_time_desc = if_else(on_time, "On time", "Delayed")
  ) %>% 
  select(-on_time)

speed_and_on_time_info %>% 
  ggplot() +
  geom_freqpoly(
    aes(x = miles_per_hour, y = ..density.., color = on_time_desc),
    na.rm = TRUE,
    binwidth = 20
  )

speed_and_on_time_info %>% 
  filter(!is.na(on_time_desc)) %>% 
  ggplot() +
  geom_histogram(
    aes(x = miles_per_hour),
    na.rm = TRUE,
    binwidth = 20
  ) +
  facet_wrap(~on_time_desc, ncol = 1)
```


## Date

```{r mutate-2}
flights %>%
  mutate(
    date_hour = as.Date(time_hour, tz = "EST"),
    date_ymd = lubridate::make_date(year, month, day)
  ) %>% 
  filter(date_hour != date_ymd)
```

## Deviation from average departure delay

```{r mutate-5}
flights %>% 
  mutate(dev = dep_delay - mean(dep_delay, na.rm = TRUE)) %>%
  ggplot() +
  geom_violin(aes(x = origin, y = dev), na.rm = TRUE)
```
