---
title: "rmarkdown exercises part 2"
author: "Kirill Müller"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
library(tidyverse)
```

## [RMarkdown workflow](https://github.com/krlmlr/vistransrep/tree/master/rmarkdown-example)

1. In your project, create two directories: `scripts` and `reports`

1. Create a script `prepare.R` in the `scripts` directory

1. Create an RMarkdown document from template, save it as `final.Rmd` in the `reports` directory.

1. Add code to `prepare.R` to transform the `flights` data in some way. (Use subsetting, add new variables, or compute a summary. Anything works.) Assign the result to a global variable using `<-`. Save this variable to a file using the `saveRDS()` function.

    Hint: Use `library(here)` and `here()` to control where the file is saved.

1. Leave only the header and the "setup" chunk in `final.Rmd`. In the "setup" chunk, insert a call to the `readRDS()` function for the file you saved in the previous step.

    Hint: Use `here` again, you should be using the same file name that you have used for `saveRDS()`.

1. Knit the document. This should work without failure (but show an empty document).

1. Create a second code chunk that shows a plot of your transformed data. Do not refer to `flights`. Knit again.


## Slides and reports

1. Choose File / New File / R Markdown... from the RStudio menu. In the dialog, select "From template" in the pane on the left-hand side and then "Ninja presentation" to create an example slide deck. Knit it.

1. What templates are available from the "rticles" package? Are any of them useful for your work?

1. Navigate to https://github.com/rstudio/bookdown-demo (or search for "bookdown demo" in a search engine). Extract the demo to a directory of your choice, and follow the instructions in the `README.md` file.
