---
title: "Scales"
author: "Kirill Müller"
date: "June 1, 2017"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
set.seed(20180516)
knitr::opts_chunk$set(cache = TRUE)
```

## Naming scales

Reusing a plot from the previous exercise:

```{r scales-1, echo=TRUE}
ggplot(data = mpg) +
  geom_point(
    mapping = aes(x = displ, y = hwy, color = factor(year))
  ) +
  geom_smooth(
    mapping = aes(x = displ, y = hwy, color = factor(year)),
    method = "lm"
  ) +
  facet_wrap(~class) +
  scale_x_continuous(name = "Displacement") +
  scale_y_continuous(name = "Fuel economy [miles per gallon]") +
  scale_color_discrete(name = "Year")
```

There exist shortcuts `xlab()` and `ylab()` for x and y labels, but not for color or fill. I recommend to stick with the explicit versions.


## Changing scales twice

A warning occurs:

```{r scales-2, echo=TRUE}
ggplot(data = mpg) +
  geom_point(mapping = aes(x = displ, y = hwy)) +
  scale_x_continuous(name = "Displacement") +
  scale_x_continuous(name = "Displacement")
```


## ColorBrewer scales

```{r scales-3}
RColorBrewer::display.brewer.all(colorblindFriendly = TRUE)
```

## A better scale for car class

```{r scales-4, echo=TRUE}
ggplot(data = mpg) +
  geom_jitter(mapping = aes(x = displ, y = hwy, color = class)) +
  scale_x_continuous(name = "Displacement") +
  scale_y_continuous(name = "Fuel economy [miles per gallon]") +
  scale_color_brewer(name = "Car class", palette = "Set2")
```
