---
title: "Select and rename"
author: "Kirill Müller"
date: "June 2, 2017"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(nycflights13)
knitr::opts_chunk$set(cache = TRUE)
```

## Select first five variables

```{r select-rename-1}
flights %>%
  select(year, month, day, dep_time, sched_dep_time)
```

```{r select-rename-2}
flights %>%
  select(year:sched_dep_time)
```

```{r select-rename-3}
## Numeric indexes work, too

flights %>%
  select(1:5)
```


## Exclude the date

```{r select-rename-4}
flights %>%
  select(-year, -month, -day)
```

```{r select-rename-5}
flights %>%
  select(-year:-day)
```

```{r select-rename-6}
## Numeric indexes work, too

flights %>%
  select(-1:-3)
```

## Departure variables

```{r select-rename-7}
## contains()

flights %>% 
  select(contains("dep_"))
```


## Move departure variables to end

```{r select-rename-8}
## everything()

flights %>%
  select(-contains("dep_"), everything(), contains("dep_"))
```
