---
title: "Separating and uniting"
author: "Kirill Müller, cynkra GmbH"
date: "June 2, 2017"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(nycflights13)
knitr::opts_chunk$set(cache = TRUE)
```

## table3

Convert `table3` to `table1` and `table2`.

```r
table3 %>%
  separate(
    ___,
    into = c("___", "___"),
    convert = TRUE
  ) %>%
  _____ %>%
  _____
```

<details>
<summary>&#x25BA; Solution:</summary>
```{r sep-unite-1}
table3 %>%
  separate(rate, into = c("cases", "population"), sep = "/", convert = TRUE)
```

```{r sep-unite-2}
table3 %>%
  separate(
    rate,
    into = c("cases", "population"),
    sep = "/",
    convert = TRUE
  ) %>%
  gather(type, count, -country, -year) %>%
  arrange(country, year, type)
```
</details>

## To table3

Convert `table2` to `table3`.

```r
table2 %>%
  _____ %>%
  unite(
    ___,
    ___, ___,
    sep = "/"
  )
```

<details>
<summary>&#x25BA; Solution:</summary>
```{r sep-unite-3}
table2 %>%
  spread(type, count) %>% 
  unite(rate, cases, population, sep = "/")
```
</details>

## Counting relations

Count the flights for each relation in the `flights` dataset, using just one grouping variable.

```r
flights %>%
  unite(
    relation,
    ___, ___,
    sep = " -> "
  ) %>%
  count(___)
```

<details>
<summary>&#x25BA; Solution:</summary>
```{r sep-unite-4}
flights %>%
  unite(
    relation,
    origin, dest,
    sep = " -> "
  ) %>%
  count(relation)
```
</details>

## More exercises

Find more exercises in Section 12.4.3 of r4ds.
