---
title: "Spreading and gathering"
author: "Kirill Müller"
date: "June 2, 2017"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
set.seed(20180516)
knitr::opts_chunk$set(cache = TRUE)
```


## table2 to table1

```{r}
table2 %>% 
  spread(type, count)
```

## table1 to table2

```{r}
table1 %>% 
  gather(type, count, cases, population)
```

```{r}
table2 %>% 
  gather(type, count, -country, -year)
```

Are the two calls symmetrical?

No, we need to arrange this result:

```{r}
table1 %>% 
  gather(type, count, -country, -year) %>% 
  arrange(country, year, type)
```


## Plot table-x

For showing one measurement:

```{r}
table1 %>%
  ggplot(aes(country, population, fill = factor(year))) +
  geom_col(position = "dodge")
```

For mapping measurement type to an aesthetic:

```{r}
table2 %>%
  ggplot(aes(country, count, fill = type)) +
  geom_col() +
  facet_wrap(~year)
```

For mapping both measurements to two aesthetics:

```{r}
table1 %>%
  ggplot(aes(population, cases, color = country)) +
  geom_point() +
  facet_wrap(~year)
```

Can also use `table1` to show only one measurement:

```{r}
table2 %>%
  filter(type == "cases") %>%
  ggplot() +
  geom_col(aes(country, count, fill = type)) +
  facet_wrap(~year)
```

## Binding

```{r}
cases_tbl <-
  table4a %>%
  gather(year, count, -country) %>%
  mutate(type = "cases")

population_tbl <-
  table4b %>% 
  gather(year, count, -country) %>%
  mutate(type = "population")

bind_rows(cases_tbl, population_tbl) %>%
  select(country, year, everything()) %>% 
  arrange(country, year, type)
```

With just one call to `gather()`:

```{r}
cases_tbl <-
  table4a %>%
  mutate(type = "cases")

population_tbl <-
  table4b %>% 
  mutate(type = "population")

bind_rows(cases_tbl, population_tbl) %>%
  gather(year, count, -country, -type) %>%
  select(country, year, everything()) %>% 
  arrange(country, year, type)
```

## Economies

```{r}
mpg %>%
  select(displ, hwy, cty) %>%
  gather(cty_hwy, value, hwy, cty) %>%
  ggplot() +
  geom_jitter(aes(displ, value, color = cty_hwy))
```
