---
title: "Summarize"
author: "Kirill Müller"
output: html_document
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(nycflights13)
knitr::opts_chunk$set(cache = TRUE)
```

## Useful summary functions

- `sum()`, `prod()`
- `mean()`, `median()`
- `sd()`, `IQR()`, `mad()`
- `min()`, `quantile()`, `max()`
- `n()`
- `sum()` and `mean()` for logical variables
- `first()`, `last()`, `nth()`

Don't forget `na.rm = TRUE` if needed!


## Mean arrival and dep delay

```{r summarize-1}
flights %>%
  summarize(mean(arr_delay, na.rm = TRUE))
```

```{r summarize-2}
flights %>%
  summarize(mean(dep_delay, na.rm = TRUE))
```

```{r summarize-3}
flights %>%
  summarize(
    mean(arr_delay, na.rm = TRUE),
    mean(dep_delay, na.rm = TRUE),
    sd(arr_delay, na.rm = TRUE),
    sd(dep_delay, na.rm = TRUE)
  )
```

```{r summarize-4}
flights %>%
  summarize_at(
    vars(arr_delay, dep_delay),
    funs(mean(., na.rm = TRUE), sd(., na.rm = TRUE))
  )
```

```{r summarize-5}
flights %>%
  group_by(origin) %>%
  summarize(
    mean(arr_delay, na.rm = TRUE),
    mean(dep_delay, na.rm = TRUE)
  )
```

```{r summarize-6}
flights %>%
  count(origin) %>%
  arrange(desc(n))
```


## Air time by carrier

```{r summarize-7}
total_airtime_by_carrier <-
  flights %>% 
    group_by(carrier) %>% 
    summarize(acc_air_time = sum(air_time, na.rm = TRUE)) %>% 
    ungroup()

total_airtime_by_carrier
```

```{r summarize-8}
total_airtime_by_carrier %>% 
  arrange(acc_air_time) %>%
  mutate(carrier = forcats::fct_inorder(carrier)) %>%
  ggplot() +
  geom_col(aes(carrier, acc_air_time / 60 / 24 / 365)) +
  coord_flip()
```

## Carriers for long-distance routes

```{r summarize-9}
carrier_arranged_by_mean_distance <-
  flights %>%
  group_by(carrier) %>% 
  summarize(mean_distance = mean(distance)) %>% 
  ungroup() %>%
  arrange(desc(mean_distance))

carrier_arranged_by_mean_distance
```

```{r summarize-10}
carrier_arranged_by_mean_distance %>% 
  ggplot() +
  geom_col(aes(x = forcats::fct_inorder(carrier), y = mean_distance))
```


## Worst plane

```{r summarize-11}
flights %>% 
  filter(is.na(dep_time)) %>%
  group_by(tailnum) %>% 
  summarize(not_departed = n()) %>% 
  ungroup() %>% 
  filter(!is.na(tailnum)) %>%
  arrange(desc(not_departed))
```

```{r summarize-12}
flights %>% 
  group_by(tailnum) %>% 
  summarize(not_departed = sum(is.na(dep_time))) %>% 
  ungroup()
```

```{r summarize-13}
flights %>% 
  filter(is.na(dep_time)) %>%
  count(tailnum) %>%
  arrange(desc(n))
```


## Short-distance routes per airline

```{r summarize-14}
flights %>%
  group_by(carrier) %>% 
  summarize(short_distance_ratio = mean(distance < 300)) %>% 
  ungroup() %>%
  arrange(desc(short_distance_ratio)) %>%
  ggplot() +
  geom_col(aes(x = forcats::fct_inorder(carrier), y = short_distance_ratio))
```
