---
title: "Summarize by multiple variables"
author: "Kirill Müller, cynkra GmbH"
output: html_document
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(nycflights13)
knitr::opts_chunk$set(cache = TRUE)
```

## Distinct airlines per relation

```{r summarize-mult-1}
flights %>%
  group_by(origin, dest, carrier) %>%
  summarize(n_flights = n()) %>%
  summarize(n_distinct_carriers = n()) %>%
  ungroup() %>% 
  arrange(desc(n_distinct_carriers))
```

Much shorter:

```{r summarize-mult-2}
flights %>%
  count(origin, dest, carrier) %>%
  count(origin, dest) %>% 
  ungroup() %>% 
  arrange(desc(nn))
```

Alternatively:

```{r summarize-mult-3}
flights %>%
  group_by(origin, dest, carrier) %>%
  tally() %>%
  tally(wt = NULL) %>%
  ungroup() %>%
  arrange(desc(nn))
```

## Cancelled flights per month per airline

```{r summarize-mult-4}
cancelled_flights <-
  flights %>% 
  group_by(carrier, month) %>% 
  summarize(share_of_cancelled = mean(is.na(dep_time))) %>%
  ungroup()

cancelled_flights
```


```{r summarize-mult-5}
cancelled_flights %>%
  ggplot() +
  geom_raster(aes(x = carrier, y = factor(month), fill = share_of_cancelled))
```
